dataset_path: "E:/VMWare/VMWare_Share/MyCode/RL-DSE v2/dataset/contest.csv"
design_space_path: "E:/VMWare/VMWare_Share/MyCode/RL-DSE v2/dataset/design-space.xlsx"

reports_folder_path: "E:/VMWare/VMWare_Share/MyCode/RL-DSE v2/reports/"
# reports_folder_path: "/ai/zsh/RL-DSE-FinalVersion/reports/"
avg_reward_curve_path: "avg_reward_2W_325.pdf"
total_reward_curve_path: "total_reward_2W_325.pdf"
epsilon_curve_path: "epsilon_curve.pdf"
preference: [0.3,0.2,0.5]
first_microarch: [4,2,2,2,12,2,2,20,2,2,16,12,16,32,64,70,54,12,12,32,4,1,16,64,4,0,2,1,8]

mem_size: 8000
max_steps: 50
tau: 0.005
k_step_update: 8
frame_skipped: 1
lr: 0.0002
max_episodes: 80 # Experiments show 80 episodes is enough for convergence.
batch_size: 25
num_epochs: 3
reward_coef: 1.732
reward_scale: 200
alpha: 0.5
punishment: -0.07

value_coef: 0.1
gamma: 0.8
entropy_coef: 1

# MicroAL settings
initialize:
  Nrted: 59
  mu: 0.1
  sig: 0.1
  # the total samples in a cluster
  batch: 15
  decoder-threshold: 1.2
  # decoder-threshold: 35
  # number for clusters
  cluster: 5
  # the iterations of the clustering
  clustering-iteration: 1000
  vis-micro-al: False